name: Coding Standards

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stylelint:
    uses: ./.github/workflows/stylelint.yml

  eslint:
    uses: ./.github/workflows/eslint.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml

  phpstan:
    uses: ./.github/workflows/phpstan.yml

  rector:
    uses: ./.github/workflows/rector.yml
