# https://github.com/marketplace/actions/deploy-wordpress-to-wp-engine

name: Deployment

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # stylelint:
  #   uses: ./.github/workflows/stylelint.yml

  # eslint:
  #   uses: ./.github/workflows/eslint.yml

  # phpcs:
  #   uses: ./.github/workflows/phpcs.yml

  # phpstan:
  #   uses: ./.github/workflows/phpstan.yml

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # needs: [stylelint,eslint,phpcs,phpstan]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Setup Node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version-file: '.nvmrc'

    # - name: Check Node version
    #   run: node -v

    # - name: Check Node version
    #   run: npm -v

    # - name: Install Node dependencies
    #   run: npm install

    # - name: Build assets
    #   run: npm run build

    - name: Deploy to Closte
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PASSWORD }}
        ARGS: "-azvr --inplace --delete"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        TARGET: /public_html/wp-content/themes/rosenfield-collection-theme-2020
        EXCLUDE: ".deployignore"
