# https://github.com/marketplace/actions/deploy-wordpress-to-wp-engine

name: Deployment

on:
  workflow_call:

jobs:
  stylelint:
    uses: ./.github/workflows/stylelint.yml

  eslint:
    uses: ./.github/workflows/eslint.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml

  phpstan:
    uses: ./.github/workflows/phpstan.yml

  rector:
    uses: ./.github/workflows/rector.yml

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [stylelint,eslint,phpcs,phpstan,rector]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Check Node version
      run: node -v

    - name: Check Node version
      run: npm -v

    - name: Install Node dependencies
      run: npm install

    - name: Build assets
      run: npm run build
      
    - name: Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.2.4
      with: 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=./.deployignore
        CACHE_CLEAR: TRUE
        SRC_PATH: "."
        REMOTE_PATH: "wp-content/themes/rosenfield-collection-theme-2020/"
        WPE_ENV: ${{ inputs.install }}
