name: PHP Coding Standards

on:
  workflow_call:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer:v2
      
    - name: PHP Version
      run:  php -v

    - name: Install Composer dependencies
      run: composer install

    - name: Lint Coding Standards
      run: composer run lint
