name: CSS Coding Standards

on:
  workflow_call:

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Check Node version
      run: node -v

    - name: Check Node version
      run: npm -v

    - name: Install Node dependencies
      run: npm install

    - name: Lint Stylesheets
      run: npm run lint-css
